import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * The Home's curation columns on a table that already has rows (T003, FR-002).
 *
 * `missao` shipped in 005, so both columns arrive by ALTER. The half worth reading is
 * `DEFAULT false NOT NULL` on `destaque_home`: `Missao.ts` declares the field `required: true`
 * with `defaultValue: false` — the shape `skill.ativa` uses — and on an existing table that
 * pair is the difference between a migration that applies and one that stops. Postgres refuses
 * a NOT NULL column on a populated table unless a default backfills the rows already there,
 * and the first lab with missions in its catalogue is where a defaultless version would fail,
 * mid-deploy. Dropping `defaultValue` from the field config would regenerate exactly that,
 * which is why `tests/migrations.test.ts` asserts the DEFAULT and not merely the column.
 *
 * `ordem_destaque` is `numeric` and NULLABLE because the field is optional: a featured mission
 * need not carry an order, and an absent one sorts last behind the declared tie-break (FR-003).
 * A NOT NULL here would be a constraint the config does not describe, and `push` — which
 * rebuilds every non-production schema from that config — would drop it straight back out,
 * leaving the database and the collections permanently disagreeing.
 *
 * Generated by `./scripts/migrate-create.sh`, and committed **with its `.json` snapshot**:
 * drizzle diffs the next generation against that file rather than against the database, so a
 * migration committed without it makes the next `migrate:create` emit these same two ADD
 * COLUMNs a second time.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "missao" ADD COLUMN "destaque_home" boolean DEFAULT false NOT NULL;
  ALTER TABLE "missao" ADD COLUMN "ordem_destaque" numeric;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "missao" DROP COLUMN "destaque_home";
  ALTER TABLE "missao" DROP COLUMN "ordem_destaque";`)
}
