import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Feature 004's schema: the avatar catalogues, `skill`, and `perfilMaker`'s new columns
 * (T010 — FR-027).
 *
 * Covers T005 (`skill`, the one **scoped** collection of the four), T006 (`tomDePele`,
 * `tomDeCabelo`), T007 (`avatarItem`) and T009 (`perfilMaker`'s personal data, avatar,
 * consent stamp and the `perfil_maker_skills` array table). The three catalogues carry **no
 * `tenant_id`** and that is the point: CLR-001 makes the art global, so only `skill` appears
 * in the multi-tenant plugin's map and only `skill` gets the column.
 *
 * **Generated by `./scripts/migrate-create.sh`, then hand-edited in exactly one way**, the
 * same way `20260907_063817_colecoes_002b.ts` was, so the next person to regenerate this file
 * knows what they will silently undo: every foreign key whose column is NOT NULL was moved
 * from Payload's generated `ON DELETE set null` to `ON DELETE restrict`. Two of them here —
 * `avatar_item.sprite_id` and `perfil_maker_skills.skill_id`.
 *
 * `required: true` generates NOT NULL and Payload generates `set null` for the matching FK.
 * The pair is unsatisfiable: deleting a referenced row runs a SET NULL that violates the NOT
 * NULL, the statement fails, and the transaction aborts with 25P02 in whatever query comes
 * next — naming neither the constraint, nor the column, nor the collection. `skill_id` is the
 * first instance to land inside an **array's** sub-table, where the derived assertion in
 * `tests/migrations.test.ts` was not yet looking; it looks there now, so a regeneration that
 * restores `set null` goes red instead of waiting for an admin to press Delete on a skill.
 *
 * `sprite_folhas_id` and `perfil_maker.avatar_render_id` keep `set null` correctly — both
 * fields are optional, so their columns are nullable and the generated action is satisfiable.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_avatar_item_categoria" AS ENUM('cabelo', 'olhos', 'nariz', 'boca', 'roupaCima', 'roupaBaixo', 'sapatos', 'oculos', 'chapeu');
  CREATE TYPE "public"."enum_avatar_item_compativel_base" AS ENUM('f', 'm');
  CREATE TYPE "public"."enum_perfil_maker_vinculo_unesp" AS ENUM('aluno', 'servidor', 'voluntario', 'sem-vinculo');
  CREATE TYPE "public"."enum_perfil_maker_escolaridade" AS ENUM('fundamental', 'medio', 'tecnico', 'superior', 'pos');
  CREATE TABLE "tom_de_pele" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"nome" varchar NOT NULL,
  	"hex" varchar NOT NULL,
  	"ordem" numeric NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "tom_de_cabelo" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"nome" varchar NOT NULL,
  	"hex" varchar NOT NULL,
  	"ordem" numeric NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "avatar_item" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"categoria" "enum_avatar_item_categoria" NOT NULL,
  	"nome" varchar NOT NULL,
  	"sprite_id" integer NOT NULL,
  	"sprite_folhas_id" integer,
  	"compativel_base" "enum_avatar_item_compativel_base",
  	"camada_z" numeric NOT NULL,
  	"pintavel" boolean,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "skill" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"ativa" boolean DEFAULT true NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "perfil_maker_skills" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"skill_id" integer NOT NULL,
  	"nivel" numeric DEFAULT 0 NOT NULL,
  	"xp" numeric DEFAULT 0 NOT NULL
  );
  
  ALTER TABLE "perfil_maker" ADD COLUMN "data_nascimento" timestamp(3) with time zone;
  ALTER TABLE "perfil_maker" ADD COLUMN "vinculo_unesp" "enum_perfil_maker_vinculo_unesp";
  ALTER TABLE "perfil_maker" ADD COLUMN "escolaridade" "enum_perfil_maker_escolaridade";
  ALTER TABLE "perfil_maker" ADD COLUMN "curso" varchar;
  ALTER TABLE "perfil_maker" ADD COLUMN "avatar_config" jsonb;
  ALTER TABLE "perfil_maker" ADD COLUMN "avatar_render_id" integer;
  ALTER TABLE "perfil_maker" ADD COLUMN "aceite_termos_em" timestamp(3) with time zone;
  ALTER TABLE "perfil_maker" ADD COLUMN "aceite_termos_versao" varchar;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "tom_de_pele_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "tom_de_cabelo_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "avatar_item_id" integer;
  ALTER TABLE "avatar_item" ADD CONSTRAINT "avatar_item_sprite_id_midia_imagem_id_fk" FOREIGN KEY ("sprite_id") REFERENCES "public"."midia_imagem"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "avatar_item" ADD CONSTRAINT "avatar_item_sprite_folhas_id_midia_imagem_id_fk" FOREIGN KEY ("sprite_folhas_id") REFERENCES "public"."midia_imagem"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "skill" ADD CONSTRAINT "skill_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "perfil_maker_skills" ADD CONSTRAINT "perfil_maker_skills_skill_id_skill_id_fk" FOREIGN KEY ("skill_id") REFERENCES "public"."skill"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "perfil_maker_skills" ADD CONSTRAINT "perfil_maker_skills_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."perfil_maker"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "tom_de_pele_updated_at_idx" ON "tom_de_pele" USING btree ("updated_at");
  CREATE INDEX "tom_de_pele_created_at_idx" ON "tom_de_pele" USING btree ("created_at");
  CREATE INDEX "tom_de_cabelo_updated_at_idx" ON "tom_de_cabelo" USING btree ("updated_at");
  CREATE INDEX "tom_de_cabelo_created_at_idx" ON "tom_de_cabelo" USING btree ("created_at");
  CREATE INDEX "avatar_item_sprite_idx" ON "avatar_item" USING btree ("sprite_id");
  CREATE INDEX "avatar_item_sprite_folhas_idx" ON "avatar_item" USING btree ("sprite_folhas_id");
  CREATE INDEX "avatar_item_updated_at_idx" ON "avatar_item" USING btree ("updated_at");
  CREATE INDEX "avatar_item_created_at_idx" ON "avatar_item" USING btree ("created_at");
  CREATE INDEX "skill_tenant_idx" ON "skill" USING btree ("tenant_id");
  CREATE INDEX "skill_slug_idx" ON "skill" USING btree ("slug");
  CREATE INDEX "skill_updated_at_idx" ON "skill" USING btree ("updated_at");
  CREATE INDEX "skill_created_at_idx" ON "skill" USING btree ("created_at");
  CREATE INDEX "perfil_maker_skills_order_idx" ON "perfil_maker_skills" USING btree ("_order");
  CREATE INDEX "perfil_maker_skills_parent_id_idx" ON "perfil_maker_skills" USING btree ("_parent_id");
  CREATE INDEX "perfil_maker_skills_skill_idx" ON "perfil_maker_skills" USING btree ("skill_id");
  ALTER TABLE "perfil_maker" ADD CONSTRAINT "perfil_maker_avatar_render_id_midia_imagem_id_fk" FOREIGN KEY ("avatar_render_id") REFERENCES "public"."midia_imagem"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_tom_de_pele_fk" FOREIGN KEY ("tom_de_pele_id") REFERENCES "public"."tom_de_pele"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_tom_de_cabelo_fk" FOREIGN KEY ("tom_de_cabelo_id") REFERENCES "public"."tom_de_cabelo"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_avatar_item_fk" FOREIGN KEY ("avatar_item_id") REFERENCES "public"."avatar_item"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "perfil_maker_avatar_render_idx" ON "perfil_maker" USING btree ("avatar_render_id");
  CREATE INDEX "payload_locked_documents_rels_tom_de_pele_id_idx" ON "payload_locked_documents_rels" USING btree ("tom_de_pele_id");
  CREATE INDEX "payload_locked_documents_rels_tom_de_cabelo_id_idx" ON "payload_locked_documents_rels" USING btree ("tom_de_cabelo_id");
  CREATE INDEX "payload_locked_documents_rels_avatar_item_id_idx" ON "payload_locked_documents_rels" USING btree ("avatar_item_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "tom_de_pele" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "tom_de_cabelo" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "avatar_item" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "skill" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "perfil_maker_skills" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "tom_de_pele" CASCADE;
  DROP TABLE "tom_de_cabelo" CASCADE;
  DROP TABLE "avatar_item" CASCADE;
  DROP TABLE "skill" CASCADE;
  DROP TABLE "perfil_maker_skills" CASCADE;
  ALTER TABLE "perfil_maker" DROP CONSTRAINT "perfil_maker_avatar_render_id_midia_imagem_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_tom_de_pele_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_tom_de_cabelo_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_avatar_item_fk";
  
  DROP INDEX "perfil_maker_avatar_render_idx";
  DROP INDEX "payload_locked_documents_rels_tom_de_pele_id_idx";
  DROP INDEX "payload_locked_documents_rels_tom_de_cabelo_id_idx";
  DROP INDEX "payload_locked_documents_rels_avatar_item_id_idx";
  ALTER TABLE "perfil_maker" DROP COLUMN "data_nascimento";
  ALTER TABLE "perfil_maker" DROP COLUMN "vinculo_unesp";
  ALTER TABLE "perfil_maker" DROP COLUMN "escolaridade";
  ALTER TABLE "perfil_maker" DROP COLUMN "curso";
  ALTER TABLE "perfil_maker" DROP COLUMN "avatar_config";
  ALTER TABLE "perfil_maker" DROP COLUMN "avatar_render_id";
  ALTER TABLE "perfil_maker" DROP COLUMN "aceite_termos_em";
  ALTER TABLE "perfil_maker" DROP COLUMN "aceite_termos_versao";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "tom_de_pele_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "tom_de_cabelo_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "avatar_item_id";
  DROP TYPE "public"."enum_avatar_item_categoria";
  DROP TYPE "public"."enum_avatar_item_compativel_base";
  DROP TYPE "public"."enum_perfil_maker_vinculo_unesp";
  DROP TYPE "public"."enum_perfil_maker_escolaridade";`)
}
