import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * The 002b eleven collections, and the `payload-locked-documents` relations T045 removed
 * (T047 — FR-001, FR-018).
 *
 * **Generated by `payload migrate:create`, then hand-edited in exactly one way**, so that the
 * next person to regenerate it knows what they will silently undo: every foreign key whose
 * column is NOT NULL was moved from Payload's generated `ON DELETE set null` to
 * `ON DELETE restrict`. Fifteen of them, plus `projeto.categoria_id`, which is the same defect
 * from an earlier migration and is corrected at the bottom of `up()` rather than by editing a
 * migration that has already run.
 *
 * `required: true` generates NOT NULL and Payload generates `set null` for the matching FK.
 * The pair is unsatisfiable: deleting a referenced row runs a SET NULL that violates the NOT
 * NULL, the statement fails, and the transaction aborts with 25P02 in whatever query comes
 * next — naming neither the constraint, nor the column, nor the collection. The same edit was
 * made by hand for `projeto.imagemCapa` before this file existed; `tests/migrations.test.ts`
 * now derives the assertion from the collections, so a regeneration that restores `set null`
 * goes red instead of waiting for a delete in production.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_artigo_status" AS ENUM('rascunho', 'em_revisao', 'publicado');
  CREATE TYPE "public"."enum_modelo3d_formatos" AS ENUM('.3mf', '.dxf', '.glb', '.gltf', '.obj', '.pdf', '.stl', '.svg', '.zip');
  CREATE TYPE "public"."enum_modelo3d_nivel_dificuldade" AS ENUM('iniciante', 'intermediario', 'avancado');
  CREATE TYPE "public"."enum_modelo3d_status" AS ENUM('rascunho', 'em_revisao', 'publicado');
  CREATE TYPE "public"."enum_aula_nivel_dificuldade" AS ENUM('basico', 'intermediario', 'avancado');
  CREATE TYPE "public"."enum_aula_status" AS ENUM('rascunho', 'em_revisao', 'publicado');
  CREATE TYPE "public"."enum_evento_tipo" AS ENUM('oficina', 'aula_presencial', 'mutirao', 'manutencao', 'evento_aberto', 'prazo_missao');
  CREATE TYPE "public"."enum_evento_status" AS ENUM('rascunho', 'publicado', 'cancelado', 'concluido');
  CREATE TYPE "public"."enum_evento_publico_alvo" AS ENUM('aberto', 'makers', 'equipe');
  CREATE TABLE "perfil_maker" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"handle" varchar NOT NULL,
  	"usuario_id" integer NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "categoria_artigo" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"ordem" numeric DEFAULT 0 NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "artigo" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"titulo" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"resumo" varchar NOT NULL,
  	"corpo" jsonb NOT NULL,
  	"capa_id" integer NOT NULL,
  	"categoria_id" integer NOT NULL,
  	"autor_id" integer NOT NULL,
  	"link_externo" varchar,
  	"curtidas" numeric DEFAULT 0 NOT NULL,
  	"downloads" numeric DEFAULT 0 NOT NULL,
  	"status" "enum_artigo_status" DEFAULT 'rascunho' NOT NULL,
  	"tempo_leitura" numeric,
  	"aprovacao_registrada" boolean DEFAULT false,
  	"aprovado_em" timestamp(3) with time zone,
  	"data_publicacao" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "artigo_texts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"text" varchar
  );
  
  CREATE TABLE "artigo_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"midia_modelo3d_id" integer,
  	"midia_documento_id" integer
  );
  
  CREATE TABLE "categoria_modelo" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"icone_id" integer NOT NULL,
  	"total_modelos" numeric DEFAULT 0 NOT NULL,
  	"ordem" numeric DEFAULT 0,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "modelo3d_formatos" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_modelo3d_formatos",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "modelo3d" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"titulo" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"descricao_curta" varchar NOT NULL,
  	"descricao_completa" jsonb,
  	"thumbnail_id" integer NOT NULL,
  	"arquivo_preview3d_id" integer,
  	"documentacao_id" integer,
  	"categoria_id" integer NOT NULL,
  	"autor_id" integer NOT NULL,
  	"nivel_dificuldade" "enum_modelo3d_nivel_dificuldade",
  	"curtidas" numeric DEFAULT 0 NOT NULL,
  	"downloads" numeric DEFAULT 0 NOT NULL,
  	"status" "enum_modelo3d_status" DEFAULT 'rascunho' NOT NULL,
  	"aprovacao_registrada" boolean DEFAULT false,
  	"aprovado_em" timestamp(3) with time zone,
  	"data_publicacao" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "modelo3d_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"midia_imagem_id" integer,
  	"midia_modelo3d_id" integer,
  	"midia_documento_id" integer
  );
  
  CREATE TABLE "aula" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"titulo" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"descricao" varchar NOT NULL,
  	"thumbnail_id" integer NOT NULL,
  	"video_url" varchar NOT NULL,
  	"duracao_min" numeric NOT NULL,
  	"ordem" numeric NOT NULL,
  	"autor_id" integer NOT NULL,
  	"nivel_dificuldade" "enum_aula_nivel_dificuldade",
  	"xp_recompensa" numeric DEFAULT 1 NOT NULL,
  	"transcricao" varchar,
  	"curtidas" numeric DEFAULT 0 NOT NULL,
  	"downloads" numeric DEFAULT 0 NOT NULL,
  	"status" "enum_aula_status" DEFAULT 'rascunho' NOT NULL,
  	"aprovacao_registrada" boolean DEFAULT false,
  	"aprovado_em" timestamp(3) with time zone,
  	"data_publicacao" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "aula_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"midia_modelo3d_id" integer,
  	"midia_documento_id" integer
  );
  
  CREATE TABLE "progresso_aula" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"usuario_id" integer NOT NULL,
  	"aula_id" integer NOT NULL,
  	"percentual_assistido" numeric DEFAULT 0 NOT NULL,
  	"concluida_em" timestamp(3) with time zone,
  	"posicao_reproducao" numeric,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "local" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"descricao" varchar,
  	"mapa_id" integer,
  	"capacidade" numeric,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "maquina" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"nome" varchar NOT NULL,
  	"icone_id" integer,
  	"manutencao_ate" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "evento" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"titulo" varchar NOT NULL,
  	"slug" varchar NOT NULL,
  	"tipo" "enum_evento_tipo" NOT NULL,
  	"descricao_curta" varchar NOT NULL,
  	"descricao_longa" jsonb,
  	"o_que_vai_fazer" jsonb,
  	"o_que_levar" jsonb,
  	"capa_id" integer,
  	"inicio_em" timestamp(3) with time zone NOT NULL,
  	"fim_em" timestamp(3) with time zone NOT NULL,
  	"dia_inteiro" boolean DEFAULT false,
  	"recorrencia" varchar,
  	"local_id" integer NOT NULL,
  	"responsavel_id" integer NOT NULL,
  	"vagas_total" numeric,
  	"inscricao_obrigatoria" boolean DEFAULT false,
  	"prazo_inscricao" timestamp(3) with time zone,
  	"xp_presenca" numeric,
  	"status" "enum_evento_status" DEFAULT 'rascunho' NOT NULL,
  	"publico_alvo" "enum_evento_publico_alvo",
  	"curtidas" numeric DEFAULT 0 NOT NULL,
  	"aprovacao_registrada" boolean DEFAULT false,
  	"aprovado_em" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "evento_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"maquina_id" integer,
  	"aula_id" integer,
  	"midia_modelo3d_id" integer,
  	"midia_documento_id" integer,
  	"midia_imagem_id" integer,
  	"projeto_id" integer
  );
  
  CREATE TABLE "curtida" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tenant_id" integer,
  	"usuario_id" integer NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "curtida_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"projeto_id" integer
  );
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_tenant_canaries_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_pending_invites_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_categoria_projeto_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_midia_imagem_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_midia_modelo3d_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_midia_documento_fk";
  
  DROP INDEX "payload_locked_documents_rels_tenant_canaries_id_idx";
  DROP INDEX "payload_locked_documents_rels_pending_invites_id_idx";
  DROP INDEX "payload_locked_documents_rels_categoria_projeto_id_idx";
  DROP INDEX "payload_locked_documents_rels_midia_imagem_id_idx";
  DROP INDEX "payload_locked_documents_rels_midia_modelo3d_id_idx";
  DROP INDEX "payload_locked_documents_rels_midia_documento_id_idx";
  ALTER TABLE "perfil_maker" ADD CONSTRAINT "perfil_maker_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "perfil_maker" ADD CONSTRAINT "perfil_maker_usuario_id_users_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "categoria_artigo" ADD CONSTRAINT "categoria_artigo_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "artigo" ADD CONSTRAINT "artigo_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "artigo" ADD CONSTRAINT "artigo_capa_id_midia_imagem_id_fk" FOREIGN KEY ("capa_id") REFERENCES "public"."midia_imagem"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "artigo" ADD CONSTRAINT "artigo_categoria_id_categoria_artigo_id_fk" FOREIGN KEY ("categoria_id") REFERENCES "public"."categoria_artigo"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "artigo" ADD CONSTRAINT "artigo_autor_id_perfil_maker_id_fk" FOREIGN KEY ("autor_id") REFERENCES "public"."perfil_maker"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "artigo_texts" ADD CONSTRAINT "artigo_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."artigo"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "artigo_rels" ADD CONSTRAINT "artigo_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."artigo"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "artigo_rels" ADD CONSTRAINT "artigo_rels_midia_modelo3d_fk" FOREIGN KEY ("midia_modelo3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "artigo_rels" ADD CONSTRAINT "artigo_rels_midia_documento_fk" FOREIGN KEY ("midia_documento_id") REFERENCES "public"."midia_documento"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "categoria_modelo" ADD CONSTRAINT "categoria_modelo_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "categoria_modelo" ADD CONSTRAINT "categoria_modelo_icone_id_midia_imagem_id_fk" FOREIGN KEY ("icone_id") REFERENCES "public"."midia_imagem"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "modelo3d_formatos" ADD CONSTRAINT "modelo3d_formatos_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_thumbnail_id_midia_imagem_id_fk" FOREIGN KEY ("thumbnail_id") REFERENCES "public"."midia_imagem"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_arquivo_preview3d_id_midia_modelo3d_id_fk" FOREIGN KEY ("arquivo_preview3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_documentacao_id_midia_documento_id_fk" FOREIGN KEY ("documentacao_id") REFERENCES "public"."midia_documento"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_categoria_id_categoria_modelo_id_fk" FOREIGN KEY ("categoria_id") REFERENCES "public"."categoria_modelo"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "modelo3d" ADD CONSTRAINT "modelo3d_autor_id_perfil_maker_id_fk" FOREIGN KEY ("autor_id") REFERENCES "public"."perfil_maker"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "modelo3d_rels" ADD CONSTRAINT "modelo3d_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "modelo3d_rels" ADD CONSTRAINT "modelo3d_rels_midia_imagem_fk" FOREIGN KEY ("midia_imagem_id") REFERENCES "public"."midia_imagem"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "modelo3d_rels" ADD CONSTRAINT "modelo3d_rels_midia_modelo3d_fk" FOREIGN KEY ("midia_modelo3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "modelo3d_rels" ADD CONSTRAINT "modelo3d_rels_midia_documento_fk" FOREIGN KEY ("midia_documento_id") REFERENCES "public"."midia_documento"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "aula" ADD CONSTRAINT "aula_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "aula" ADD CONSTRAINT "aula_thumbnail_id_midia_imagem_id_fk" FOREIGN KEY ("thumbnail_id") REFERENCES "public"."midia_imagem"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "aula" ADD CONSTRAINT "aula_autor_id_perfil_maker_id_fk" FOREIGN KEY ("autor_id") REFERENCES "public"."perfil_maker"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "aula_rels" ADD CONSTRAINT "aula_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."aula"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "aula_rels" ADD CONSTRAINT "aula_rels_midia_modelo3d_fk" FOREIGN KEY ("midia_modelo3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "aula_rels" ADD CONSTRAINT "aula_rels_midia_documento_fk" FOREIGN KEY ("midia_documento_id") REFERENCES "public"."midia_documento"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "progresso_aula" ADD CONSTRAINT "progresso_aula_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "progresso_aula" ADD CONSTRAINT "progresso_aula_usuario_id_users_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "progresso_aula" ADD CONSTRAINT "progresso_aula_aula_id_aula_id_fk" FOREIGN KEY ("aula_id") REFERENCES "public"."aula"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "local" ADD CONSTRAINT "local_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "local" ADD CONSTRAINT "local_mapa_id_midia_imagem_id_fk" FOREIGN KEY ("mapa_id") REFERENCES "public"."midia_imagem"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "maquina" ADD CONSTRAINT "maquina_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "maquina" ADD CONSTRAINT "maquina_icone_id_midia_imagem_id_fk" FOREIGN KEY ("icone_id") REFERENCES "public"."midia_imagem"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "evento" ADD CONSTRAINT "evento_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "evento" ADD CONSTRAINT "evento_capa_id_midia_imagem_id_fk" FOREIGN KEY ("capa_id") REFERENCES "public"."midia_imagem"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "evento" ADD CONSTRAINT "evento_local_id_local_id_fk" FOREIGN KEY ("local_id") REFERENCES "public"."local"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "evento" ADD CONSTRAINT "evento_responsavel_id_perfil_maker_id_fk" FOREIGN KEY ("responsavel_id") REFERENCES "public"."perfil_maker"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."evento"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_maquina_fk" FOREIGN KEY ("maquina_id") REFERENCES "public"."maquina"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_aula_fk" FOREIGN KEY ("aula_id") REFERENCES "public"."aula"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_midia_modelo3d_fk" FOREIGN KEY ("midia_modelo3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_midia_documento_fk" FOREIGN KEY ("midia_documento_id") REFERENCES "public"."midia_documento"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_midia_imagem_fk" FOREIGN KEY ("midia_imagem_id") REFERENCES "public"."midia_imagem"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "evento_rels" ADD CONSTRAINT "evento_rels_projeto_fk" FOREIGN KEY ("projeto_id") REFERENCES "public"."projeto"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "curtida" ADD CONSTRAINT "curtida_tenant_id_organizations_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "curtida" ADD CONSTRAINT "curtida_usuario_id_users_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
  ALTER TABLE "curtida_rels" ADD CONSTRAINT "curtida_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."curtida"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "curtida_rels" ADD CONSTRAINT "curtida_rels_projeto_fk" FOREIGN KEY ("projeto_id") REFERENCES "public"."projeto"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "perfil_maker_tenant_idx" ON "perfil_maker" USING btree ("tenant_id");
  CREATE INDEX "perfil_maker_handle_idx" ON "perfil_maker" USING btree ("handle");
  CREATE INDEX "perfil_maker_usuario_idx" ON "perfil_maker" USING btree ("usuario_id");
  CREATE INDEX "perfil_maker_updated_at_idx" ON "perfil_maker" USING btree ("updated_at");
  CREATE INDEX "perfil_maker_created_at_idx" ON "perfil_maker" USING btree ("created_at");
  CREATE INDEX "categoria_artigo_tenant_idx" ON "categoria_artigo" USING btree ("tenant_id");
  CREATE INDEX "categoria_artigo_slug_idx" ON "categoria_artigo" USING btree ("slug");
  CREATE INDEX "categoria_artigo_updated_at_idx" ON "categoria_artigo" USING btree ("updated_at");
  CREATE INDEX "categoria_artigo_created_at_idx" ON "categoria_artigo" USING btree ("created_at");
  CREATE INDEX "artigo_tenant_idx" ON "artigo" USING btree ("tenant_id");
  CREATE INDEX "artigo_slug_idx" ON "artigo" USING btree ("slug");
  CREATE INDEX "artigo_capa_idx" ON "artigo" USING btree ("capa_id");
  CREATE INDEX "artigo_categoria_idx" ON "artigo" USING btree ("categoria_id");
  CREATE INDEX "artigo_autor_idx" ON "artigo" USING btree ("autor_id");
  CREATE INDEX "artigo_updated_at_idx" ON "artigo" USING btree ("updated_at");
  CREATE INDEX "artigo_created_at_idx" ON "artigo" USING btree ("created_at");
  CREATE INDEX "artigo_texts_order_parent" ON "artigo_texts" USING btree ("order","parent_id");
  CREATE INDEX "artigo_rels_order_idx" ON "artigo_rels" USING btree ("order");
  CREATE INDEX "artigo_rels_parent_idx" ON "artigo_rels" USING btree ("parent_id");
  CREATE INDEX "artigo_rels_path_idx" ON "artigo_rels" USING btree ("path");
  CREATE INDEX "artigo_rels_midia_modelo3d_id_idx" ON "artigo_rels" USING btree ("midia_modelo3d_id");
  CREATE INDEX "artigo_rels_midia_documento_id_idx" ON "artigo_rels" USING btree ("midia_documento_id");
  CREATE INDEX "categoria_modelo_tenant_idx" ON "categoria_modelo" USING btree ("tenant_id");
  CREATE INDEX "categoria_modelo_slug_idx" ON "categoria_modelo" USING btree ("slug");
  CREATE INDEX "categoria_modelo_icone_idx" ON "categoria_modelo" USING btree ("icone_id");
  CREATE INDEX "categoria_modelo_updated_at_idx" ON "categoria_modelo" USING btree ("updated_at");
  CREATE INDEX "categoria_modelo_created_at_idx" ON "categoria_modelo" USING btree ("created_at");
  CREATE INDEX "modelo3d_formatos_order_idx" ON "modelo3d_formatos" USING btree ("order");
  CREATE INDEX "modelo3d_formatos_parent_idx" ON "modelo3d_formatos" USING btree ("parent_id");
  CREATE INDEX "modelo3d_tenant_idx" ON "modelo3d" USING btree ("tenant_id");
  CREATE INDEX "modelo3d_slug_idx" ON "modelo3d" USING btree ("slug");
  CREATE INDEX "modelo3d_thumbnail_idx" ON "modelo3d" USING btree ("thumbnail_id");
  CREATE INDEX "modelo3d_arquivo_preview3d_idx" ON "modelo3d" USING btree ("arquivo_preview3d_id");
  CREATE INDEX "modelo3d_documentacao_idx" ON "modelo3d" USING btree ("documentacao_id");
  CREATE INDEX "modelo3d_categoria_idx" ON "modelo3d" USING btree ("categoria_id");
  CREATE INDEX "modelo3d_autor_idx" ON "modelo3d" USING btree ("autor_id");
  CREATE INDEX "modelo3d_updated_at_idx" ON "modelo3d" USING btree ("updated_at");
  CREATE INDEX "modelo3d_created_at_idx" ON "modelo3d" USING btree ("created_at");
  CREATE INDEX "modelo3d_rels_order_idx" ON "modelo3d_rels" USING btree ("order");
  CREATE INDEX "modelo3d_rels_parent_idx" ON "modelo3d_rels" USING btree ("parent_id");
  CREATE INDEX "modelo3d_rels_path_idx" ON "modelo3d_rels" USING btree ("path");
  CREATE INDEX "modelo3d_rels_midia_imagem_id_idx" ON "modelo3d_rels" USING btree ("midia_imagem_id");
  CREATE INDEX "modelo3d_rels_midia_modelo3d_id_idx" ON "modelo3d_rels" USING btree ("midia_modelo3d_id");
  CREATE INDEX "modelo3d_rels_midia_documento_id_idx" ON "modelo3d_rels" USING btree ("midia_documento_id");
  CREATE INDEX "aula_tenant_idx" ON "aula" USING btree ("tenant_id");
  CREATE INDEX "aula_slug_idx" ON "aula" USING btree ("slug");
  CREATE INDEX "aula_thumbnail_idx" ON "aula" USING btree ("thumbnail_id");
  CREATE INDEX "aula_ordem_idx" ON "aula" USING btree ("ordem");
  CREATE INDEX "aula_autor_idx" ON "aula" USING btree ("autor_id");
  CREATE INDEX "aula_updated_at_idx" ON "aula" USING btree ("updated_at");
  CREATE INDEX "aula_created_at_idx" ON "aula" USING btree ("created_at");
  CREATE INDEX "aula_rels_order_idx" ON "aula_rels" USING btree ("order");
  CREATE INDEX "aula_rels_parent_idx" ON "aula_rels" USING btree ("parent_id");
  CREATE INDEX "aula_rels_path_idx" ON "aula_rels" USING btree ("path");
  CREATE INDEX "aula_rels_midia_modelo3d_id_idx" ON "aula_rels" USING btree ("midia_modelo3d_id");
  CREATE INDEX "aula_rels_midia_documento_id_idx" ON "aula_rels" USING btree ("midia_documento_id");
  CREATE INDEX "progresso_aula_tenant_idx" ON "progresso_aula" USING btree ("tenant_id");
  CREATE INDEX "progresso_aula_usuario_idx" ON "progresso_aula" USING btree ("usuario_id");
  CREATE INDEX "progresso_aula_aula_idx" ON "progresso_aula" USING btree ("aula_id");
  CREATE INDEX "progresso_aula_updated_at_idx" ON "progresso_aula" USING btree ("updated_at");
  CREATE INDEX "progresso_aula_created_at_idx" ON "progresso_aula" USING btree ("created_at");
  CREATE UNIQUE INDEX "usuario_aula_idx" ON "progresso_aula" USING btree ("usuario_id","aula_id");
  CREATE INDEX "local_tenant_idx" ON "local" USING btree ("tenant_id");
  CREATE INDEX "local_mapa_idx" ON "local" USING btree ("mapa_id");
  CREATE INDEX "local_updated_at_idx" ON "local" USING btree ("updated_at");
  CREATE INDEX "local_created_at_idx" ON "local" USING btree ("created_at");
  CREATE INDEX "maquina_tenant_idx" ON "maquina" USING btree ("tenant_id");
  CREATE INDEX "maquina_icone_idx" ON "maquina" USING btree ("icone_id");
  CREATE INDEX "maquina_updated_at_idx" ON "maquina" USING btree ("updated_at");
  CREATE INDEX "maquina_created_at_idx" ON "maquina" USING btree ("created_at");
  CREATE INDEX "evento_tenant_idx" ON "evento" USING btree ("tenant_id");
  CREATE INDEX "evento_slug_idx" ON "evento" USING btree ("slug");
  CREATE INDEX "evento_capa_idx" ON "evento" USING btree ("capa_id");
  CREATE INDEX "evento_inicio_em_idx" ON "evento" USING btree ("inicio_em");
  CREATE INDEX "evento_local_idx" ON "evento" USING btree ("local_id");
  CREATE INDEX "evento_responsavel_idx" ON "evento" USING btree ("responsavel_id");
  CREATE INDEX "evento_updated_at_idx" ON "evento" USING btree ("updated_at");
  CREATE INDEX "evento_created_at_idx" ON "evento" USING btree ("created_at");
  CREATE INDEX "evento_rels_order_idx" ON "evento_rels" USING btree ("order");
  CREATE INDEX "evento_rels_parent_idx" ON "evento_rels" USING btree ("parent_id");
  CREATE INDEX "evento_rels_path_idx" ON "evento_rels" USING btree ("path");
  CREATE INDEX "evento_rels_maquina_id_idx" ON "evento_rels" USING btree ("maquina_id");
  CREATE INDEX "evento_rels_aula_id_idx" ON "evento_rels" USING btree ("aula_id");
  CREATE INDEX "evento_rels_midia_modelo3d_id_idx" ON "evento_rels" USING btree ("midia_modelo3d_id");
  CREATE INDEX "evento_rels_midia_documento_id_idx" ON "evento_rels" USING btree ("midia_documento_id");
  CREATE INDEX "evento_rels_midia_imagem_id_idx" ON "evento_rels" USING btree ("midia_imagem_id");
  CREATE INDEX "evento_rels_projeto_id_idx" ON "evento_rels" USING btree ("projeto_id");
  CREATE INDEX "curtida_tenant_idx" ON "curtida" USING btree ("tenant_id");
  CREATE INDEX "curtida_usuario_idx" ON "curtida" USING btree ("usuario_id");
  CREATE INDEX "curtida_updated_at_idx" ON "curtida" USING btree ("updated_at");
  CREATE INDEX "curtida_created_at_idx" ON "curtida" USING btree ("created_at");
  CREATE INDEX "curtida_rels_order_idx" ON "curtida_rels" USING btree ("order");
  CREATE INDEX "curtida_rels_parent_idx" ON "curtida_rels" USING btree ("parent_id");
  CREATE INDEX "curtida_rels_path_idx" ON "curtida_rels" USING btree ("path");
  CREATE INDEX "curtida_rels_projeto_id_idx" ON "curtida_rels" USING btree ("projeto_id");
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "tenant_canaries_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "pending_invites_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "categoria_projeto_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "midia_imagem_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "midia_modelo3d_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "midia_documento_id";
  ALTER TABLE "projeto" DROP CONSTRAINT "projeto_categoria_id_categoria_projeto_id_fk";
  ALTER TABLE "projeto" ADD CONSTRAINT "projeto_categoria_id_categoria_projeto_id_fk" FOREIGN KEY ("categoria_id") REFERENCES "public"."categoria_projeto"("id") ON DELETE restrict ON UPDATE no action;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "perfil_maker" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "categoria_artigo" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "artigo" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "artigo_texts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "artigo_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "categoria_modelo" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "modelo3d_formatos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "modelo3d" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "modelo3d_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "aula" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "aula_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "progresso_aula" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "local" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "maquina" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "evento" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "evento_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "curtida" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "curtida_rels" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "perfil_maker" CASCADE;
  DROP TABLE "categoria_artigo" CASCADE;
  DROP TABLE "artigo" CASCADE;
  DROP TABLE "artigo_texts" CASCADE;
  DROP TABLE "artigo_rels" CASCADE;
  DROP TABLE "categoria_modelo" CASCADE;
  DROP TABLE "modelo3d_formatos" CASCADE;
  DROP TABLE "modelo3d" CASCADE;
  DROP TABLE "modelo3d_rels" CASCADE;
  DROP TABLE "aula" CASCADE;
  DROP TABLE "aula_rels" CASCADE;
  DROP TABLE "progresso_aula" CASCADE;
  DROP TABLE "local" CASCADE;
  DROP TABLE "maquina" CASCADE;
  DROP TABLE "evento" CASCADE;
  DROP TABLE "evento_rels" CASCADE;
  DROP TABLE "curtida" CASCADE;
  DROP TABLE "curtida_rels" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "tenant_canaries_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "pending_invites_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "categoria_projeto_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "midia_imagem_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "midia_modelo3d_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "midia_documento_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_tenant_canaries_fk" FOREIGN KEY ("tenant_canaries_id") REFERENCES "public"."tenant_canaries"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pending_invites_fk" FOREIGN KEY ("pending_invites_id") REFERENCES "public"."pending_invites"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_categoria_projeto_fk" FOREIGN KEY ("categoria_projeto_id") REFERENCES "public"."categoria_projeto"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_midia_imagem_fk" FOREIGN KEY ("midia_imagem_id") REFERENCES "public"."midia_imagem"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_midia_modelo3d_fk" FOREIGN KEY ("midia_modelo3d_id") REFERENCES "public"."midia_modelo3d"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_midia_documento_fk" FOREIGN KEY ("midia_documento_id") REFERENCES "public"."midia_documento"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_tenant_canaries_id_idx" ON "payload_locked_documents_rels" USING btree ("tenant_canaries_id");
  CREATE INDEX "payload_locked_documents_rels_pending_invites_id_idx" ON "payload_locked_documents_rels" USING btree ("pending_invites_id");
  CREATE INDEX "payload_locked_documents_rels_categoria_projeto_id_idx" ON "payload_locked_documents_rels" USING btree ("categoria_projeto_id");
  CREATE INDEX "payload_locked_documents_rels_midia_imagem_id_idx" ON "payload_locked_documents_rels" USING btree ("midia_imagem_id");
  CREATE INDEX "payload_locked_documents_rels_midia_modelo3d_id_idx" ON "payload_locked_documents_rels" USING btree ("midia_modelo3d_id");
  CREATE INDEX "payload_locked_documents_rels_midia_documento_id_idx" ON "payload_locked_documents_rels" USING btree ("midia_documento_id");
  DROP TYPE "public"."enum_artigo_status";
  DROP TYPE "public"."enum_modelo3d_formatos";
  DROP TYPE "public"."enum_modelo3d_nivel_dificuldade";
  DROP TYPE "public"."enum_modelo3d_status";
  DROP TYPE "public"."enum_aula_nivel_dificuldade";
  DROP TYPE "public"."enum_aula_status";
  DROP TYPE "public"."enum_evento_tipo";
  DROP TYPE "public"."enum_evento_status";
  DROP TYPE "public"."enum_evento_publico_alvo";
  ALTER TABLE "projeto" DROP CONSTRAINT "projeto_categoria_id_categoria_projeto_id_fk";
  ALTER TABLE "projeto" ADD CONSTRAINT "projeto_categoria_id_categoria_projeto_id_fk" FOREIGN KEY ("categoria_id") REFERENCES "public"."categoria_projeto"("id") ON DELETE set null ON UPDATE no action;`)
}
